# Generated by Django 2.0.6 on 2019-02-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190215_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_mount',
            new_name='order_amount',
        ),
    ]
