# Generated by Django 2.0.6 on 2019-01-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerfyCode',
            new_name='VerifyCode',
        ),
    ]
